# Generated by Django 5.2.17 on 2026-09-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.CharField(blank=True, max_length=100, verbose_name='客户')),
                ('channel', models.CharField(choices=[('email', '邮件'), ('whatsapp', 'WhatsApp'), ('alibaba', 'Alibaba'), ('other', '其他')], default='email', max_length=20, verbose_name='渠道')),
                ('raw_text', models.TextField(blank=True, verbose_name='询价原文')),
                ('image', models.ImageField(blank=True, upload_to='inquiries/', verbose_name='图片')),
                ('image_result', models.JSONField(blank=True, null=True, verbose_name='图片识别结果')),
                ('quote_email', models.TextField(blank=True, verbose_name='报价邮件')),
                ('elapsed_ms', models.PositiveIntegerField(default=0, verbose_name='处理耗时(ms)')),
            ],
            options={
                'verbose_name': '询价',
                'verbose_name_plural': '询价',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('query', models.CharField(max_length=500, verbose_name='询价行')),
                ('parsed', models.JSONField(default=dict, verbose_name='解析结果')),
                ('candidates', models.JSONField(default=list, verbose_name='候选快照')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单价(USD)')),
                ('feedback', models.CharField(blank=True, choices=[('correct', '正确'), ('wrong', '错误')], max_length=10, verbose_name='反馈')),
                ('feedback_note', models.CharField(blank=True, max_length=300, verbose_name='反馈备注')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inquiry.inquiry')),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='选中产品')),
            ],
            options={
                'verbose_name': '询价行',
                'verbose_name_plural': '询价行',
                'ordering': ['inquiry', 'position'],
            },
        ),
    ]
