# Generated by Django 5.2.17 on 2026-09-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('alibaba', 'Alibaba'), ('shopify', 'Shopify')], max_length=10, verbose_name='平台')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('keywords', models.JSONField(default=list, verbose_name='关键词')),
                ('bullets', models.JSONField(default=list, verbose_name='卖点')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('faq', models.JSONField(default=list, verbose_name='FAQ')),
                ('warnings', models.JSONField(default=list, verbose_name='校验提示')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认')], default='draft', max_length=10, verbose_name='状态')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.product')),
            ],
            options={
                'verbose_name': '上架文案',
                'verbose_name_plural': '上架文案',
                'ordering': ['-updated_at'],
            },
        ),
    ]
