# Generated by Django 5.2.17 on 2026-09-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='供应商')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='地区')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='联系人/方式')),
                ('product_lines', models.CharField(blank=True, max_length=300, verbose_name='主营产品线')),
                ('rating', models.PositiveSmallIntegerField(default=3, verbose_name='评级(1-5)')),
                ('quality_notes', models.TextField(blank=True, verbose_name='质量记录')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier_part_no', models.CharField(blank=True, max_length=60, verbose_name='供应商料号')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='成本价')),
                ('currency', models.CharField(choices=[('CNY', 'CNY'), ('USD', 'USD'), ('EUR', 'EUR')], default='CNY', max_length=3, verbose_name='币种')),
                ('moq', models.PositiveIntegerField(blank=True, null=True, verbose_name='MOQ')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='交期(天)')),
                ('packaging', models.CharField(blank=True, max_length=200, verbose_name='包装')),
                ('quoted_at', models.DateField(verbose_name='报价日期')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.product', verbose_name='产品')),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.importrow', verbose_name='来源导入行')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商报价',
                'verbose_name_plural': '供应商报价',
                'ordering': ['-quoted_at'],
            },
        ),
    ]
