# Generated by Django 5.2.17 on 2026-09-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(db_index=True, max_length=40, verbose_name='规则')),
                ('category', models.CharField(choices=[('missing', '缺失'), ('duplicate', '重复'), ('format', '格式'), ('consistency', '一致性')], max_length=20, verbose_name='类别')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10, verbose_name='严重度')),
                ('field', models.CharField(blank=True, max_length=50, verbose_name='字段')),
                ('message', models.CharField(max_length=300, verbose_name='说明')),
                ('resolved', models.BooleanField(default=False, verbose_name='已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='catalog.product')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
            ],
            options={
                'verbose_name': '数据问题',
                'verbose_name_plural': '数据问题',
                'ordering': ['resolved', 'severity', 'rule_code'],
            },
        ),
    ]
