# Generated by Django 5.2.17 on 2026-09-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataissue',
            options={'ordering': ['resolved', 'rule_code'], 'verbose_name': '数据问题', 'verbose_name_plural': '数据问题'},
        ),
    ]
