# Generated by Django 5.2.17 on 2026-09-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, verbose_name='任务')),
                ('model', models.CharField(max_length=100, verbose_name='模型')),
                ('prompt_code', models.CharField(blank=True, max_length=50, verbose_name='提示词')),
                ('prompt_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='提示词版本')),
                ('request', models.JSONField(default=dict, verbose_name='请求')),
                ('response', models.TextField(blank=True, verbose_name='响应')),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='耗时(ms)')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('error', models.TextField(blank=True, verbose_name='错误')),
                ('is_mock', models.BooleanField(default=False, verbose_name='Mock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': 'AI 调用日志',
                'verbose_name_plural': 'AI 调用日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'ordering': ['code', '-version'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='uniq_prompt_version')],
            },
        ),
    ]
