# Generated by Django 5.2.17 on 2026-09-17 05:59

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品牌')),
                ('type', models.CharField(choices=[('oem', '主机厂 OEM'), ('aftermarket', '副厂 Aftermarket')], max_length=20, verbose_name='类型')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='品牌')),
                ('series', models.CharField(max_length=50, verbose_name='系列')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='起始年份')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='截止年份')),
                ('engine', models.CharField(blank=True, max_length=50, verbose_name='发动机')),
            ],
            options={
                'verbose_name': '车型',
                'verbose_name_plural': '车型',
                'ordering': ['make', 'series'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名')),
                ('margin_rate', models.DecimalField(decimal_places=2, default=0.3, max_digits=4, verbose_name='毛利率')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='上级')),
            ],
            options={
                'verbose_name': '品类',
                'verbose_name_plural': '品类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='SKU')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名')),
                ('name_cn', models.CharField(blank=True, max_length=200, verbose_name='中文名')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='规格')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='重量(kg)')),
                ('package_l_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='包装长(cm)')),
                ('package_w_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='包装宽(cm)')),
                ('package_h_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='包装高(cm)')),
                ('qty_per_package', models.PositiveIntegerField(blank=True, null=True, verbose_name='每包数量')),
                ('description_en', models.TextField(blank=True, verbose_name='英文描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '在售'), ('archived', '已归档')], default='active', max_length=10, verbose_name='状态')),
                ('completeness_score', models.PositiveSmallIntegerField(default=0, verbose_name='完整度')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='品类')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.product', verbose_name='合并至')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, verbose_name='号码(原始)')),
                ('normalized', models.CharField(db_index=True, editable=False, max_length=60, verbose_name='号码(归一化)')),
                ('type', models.CharField(choices=[('oe', 'OE 原厂号'), ('cross', 'Cross 参考号'), ('supplier', '供应商料号')], max_length=10, verbose_name='类型')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='品牌')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='catalog.product')),
            ],
            options={
                'verbose_name': '零件号',
                'verbose_name_plural': '零件号',
                'ordering': ['type', 'normalized'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='图片')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主图')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
            },
        ),
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.vehiclemodel', verbose_name='车型')),
            ],
            options={
                'verbose_name': '适配车型',
                'verbose_name_plural': '适配车型',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='product_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='partnumber',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized'], name='partnumber_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='partnumber',
            constraint=models.UniqueConstraint(fields=('product', 'normalized', 'brand'), name='uniq_product_number_brand'),
        ),
        migrations.AddConstraint(
            model_name='fitment',
            constraint=models.UniqueConstraint(fields=('product', 'vehicle_model'), name='uniq_fitment'),
        ),
    ]
