# Generated by Django 5.2.17 on 2026-09-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file', models.FileField(upload_to='imports/', verbose_name='文件')),
                ('file_type', models.CharField(max_length=10, verbose_name='类型')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('parsing', '解析中'), ('reviewing', '待审核'), ('done', '已完成'), ('failed', '失败')], default='uploaded', max_length=10, verbose_name='状态')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='列映射')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='统计')),
                ('log', models.TextField(blank=True, verbose_name='日志')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(verbose_name='行号')),
                ('raw', models.JSONField(default=dict, verbose_name='原始数据')),
                ('extracted', models.JSONField(default=dict, verbose_name='抽取结果')),
                ('errors', models.JSONField(default=list, verbose_name='校验问题')),
                ('match_method', models.CharField(blank=True, max_length=20, verbose_name='匹配方式')),
                ('confidence', models.PositiveSmallIntegerField(default=0, verbose_name='置信度')),
                ('preselected', models.BooleanField(default=False, verbose_name='预选通过')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('new_product', '已新建SKU')], default='pending', max_length=12, verbose_name='状态')),
            ],
            options={
                'verbose_name': '导入行',
                'verbose_name_plural': '导入行',
                'ordering': ['batch', 'row_index'],
            },
        ),
    ]
